syntax = "proto3";

package wheelbid.v1;
import "google/protobuf/timestamp.proto";
import "wheelbid/v1/features.proto";

message Car {
  string car_id = 1;
  string name = 2;
  string desc = 3;
  string location = 4;
  string address = 5;
  string model_type = 6;
  int32 base_price_INR = 7;
  int32 current_bid = 8;
  bool auctionActive = 9;
  optional google.protobuf.Timestamp auctionClosingTime = 10;
  Features features = 11;
}

service CarService {
  rpc getCarDetails(CarDetailsRequest) returns (Car);
}

message CarDetailsRequest{
  string carId = 1;
}
